services:
  - type: web
    name: extrato-pagstar
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"